name: SonarQube Analysis (Python)

on:
  push:
    branches: [ "main" ]   # Community Edition: analyze your main branch
  # Developer+ editions can also analyze PRs and multiple branches

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Recommended for better analysis relevance

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps & run tests with coverage
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # run tests & produce coverage.xml (Cobertura format)
          coverage run -m pytest
          coverage xml

      # Official SonarQube Scan action
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # OPTIONAL: Fail the pipeline if Quality Gate is red (Server-only)
      - name: Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          pollingTimeoutSec: 600
